### ISSUE TITLE
Decomposing a time series on a rolling window basis.

### ISSUE THREAD

**Issue by ghost** [0zean/MODWT-MARS#1]
Hi there Nicholas i'm doing research for my own paper, when i came across your repository,
although i am not quite fluent in R i can see from the code that you have transformed the entirety of the data in one batch, depending on the decomposition algorithm used there could be leaks from data as far as t+3, have you tried an implementation using a rolling window transform.

Best

**Comment by 0zean** [comment]
Hi, I know this is a quite late, not sure why I didn't see this post earlier, but you are correct. This work presents my code implementation of the mentioned paper in the README but with MARS rather than SVM or a Neural Net. This is a common problem in quantitative finance papers where the authors misuse signal processing techniques and get very misleading results as seen in the paper and in this project. There are significant boundary effects that make even the one-step ahead predictions useless from the accumulated errors in boundary coefficients. Even a moving window is not enough to negate these boundary effects. More techniques would be needed for an on-line type of wavelet forecasting using rolling windows. It is also possible to perform a two-stage decomposition to remove edge effects in predictions as shown in this [paper](https://www.researchgate.net/publication/338082586_Two-stage_Variational_Mode_Decomposition_and_Support_Vector_Regression_for_Streamflow_Forecasting)
